# Beneden aan als thuis
- alias: "ground_floor: Turn on if coming home after sunset"
  trigger:
    platform: state
    entity_id: device_tracker.manon, device_tracker.manon_phone, device_tracker.oneplus_hans, device_tracker.hans, device_tracker.androide1d1725d21f4419c
    from: 'not_home'
    to: 'home'
  condition:
     condition: and
     conditions:
       - condition: or
         conditions:
           - condition: sun
             after: sunset
           - condition: time
             before: '00:30:00'
  action:
    service: light.turn_on
    entity_id: light.Keuken_kast, light.Keuken_spots, light.Keuken_spots_wijn

########################################################################
# Beneden aan als thuis: na zons ondergang
- alias: "ground floor: Turn on sunset and home"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.androide1d1725d21f4419c
            state: 'home'
          - condition: state
            entity_id: device_tracker.manon
            state: 'home'
          - condition: state
            entity_id: device_tracker.manon_phone
            state: 'home'
          - condition: state
            entity_id: device_tracker.hans_oneplus
            state: 'home'
  action:
    service: light.turn_on
    entity_id: light.Keuken_kast, light.Keuken_spots, light.Keuken_spots_wijn

########################################################################
# beneden light: Turn off at 1
- alias: "Groundfloor: Turn off at midnight"
  trigger:
    platform: time
    hours: 1
    minutes: 0
    seconds: 0
  action:
    service: light.turn_off
    entity_id: light.Keuken_kast, light.Keuken_spots, light.Keuken_spots_wijn
