- alias: "Voorkamer: Turn on at sunset + 30min"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: light.turn_on
    entity_id: light.Voorkamer_spots

- alias: "Voorkamer: Turn off at midnight"
  trigger:
    platform: time
    hours: 1
    minutes: 0
    seconds: 0
  action:
    service: light.turn_off
    entity_id: light.Voorkamer_spots

- alias: "Boekenstand: Turn on if Voorkamer On"
  trigger:
    platform: state
    entity_id: light.voorkamer_spots
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.neo_coolcam_power_plug_12a_switch_2

- alias: "hout: Turn on if Voorkamer On"
  trigger:
    platform: state
    entity_id: light.voorkamer_spots
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.neo_coolcam_power_plug_12a_switch

- alias: "Boekenstand: Turn on if Voorkamer Off"
  trigger:
    platform: state
    entity_id: light.voorkamer_spots
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.neo_coolcam_power_plug_12a_switch_2

- alias: "hout: Turn on if Voorkamer Off"
  trigger:
    platform: state
    entity_id: light.voorkamer_spots
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.neo_coolcam_power_plug_12a_switch
